exports [    
    {
        name: '',
        price: '',
        icon: '',
        source: '',
        page: '',
    },
    {
        name: '',
        price: '',
        icon: '',
        source: '',
        page: '',
    },
    {
        name: '',
        price: '',
        icon: '',
        source: '',
        page: '',
    },
    {
        name: '',
        price: '',
        icon: '',
        source: '',
        page: '',
    },
    {
        name: '',
        price: '',
        icon: '',
        source: '',
        page: '',
    },
    {
        name: '',
        price: '',
        icon: '',
        source: '',
        page: '',
    },
    {
        name: '',
        price: '',
        icon: '',
        source: '',
        page: '',
    },
    {
        name: '',
        price: '',
        icon: '',
        source: '',
        page: '',
    },
    {
        name: '',
        price: '',
        icon: '',
        source: '',
        page: '',
    },
    {
        name: '',
        price: '',
        icon: '',
        source: '',
        page: '',
    },
    {
        name: '',
        price: '',
        icon: '',
        source: '',
        page: '',
    },
    {
        name: '',
        price: '',
        icon: '',
        source: '',
        page: '',
    },
    {
        name: '',
        price: '',
        icon: '',
        source: '',
        page: '',
    }
]