 const meleeWeapons = [
    {
        name: 'Buckler',
        price: 2,
        coin: 'g',
        icon: '',
        availability: 4,
        page: '110',
    },
    {
        name: 'Dagger',
        price: 1,
        coin: 'g',
        icon: '',
        availability: 5,
        page: '110',
    },
    {
        name: 'Demilance (Cavalry Spear)',
        price: 20,
        coin: 'g',
        icon: '',
        availability: 3,
        page: '110',
    },
    {
        name: 'Flail',
        price: 15,
        coin: 'g',
        icon: '',
        availability: 3,
        page: '110',
    },
    {
        name: 'Foil',
        price: 18,
        coin: 'g',
        icon: '',
        availability: 2,
        page: '110',
    },
    {
        name: 'Gaunglet/Knuckle-duster',
        price: 1,
        coin: 'g',
        icon: '',
        availability: 5,
        page: '110',
    },
    {
        name: 'Great Weapon',
        price: 20,
        coin: 'g',
        icon: '',
        availability: 4,
        page: '110',
    },
    {
        name: 'Halberd',
        price: 15,
        coin: 'g',
        icon: '',
        availability: 5,
        page: '110',
    },
    {
        name: 'Hand Weapon',
        price: 10,
        coin: 'g',
        icon: '',
        availability: 5,
        page: '110',
    },
    {
        name: 'Lance',
        price: 15,
        coin: 'g',
        icon: '',
        availability: 2,
        page: '110',
    },
    {
        name: 'Main Gauche',
        price: 4,
        coin: 'g',
        icon: '',
        availability: 3,
        page: '110',
    },
    {
        name: 'Morning Star',
        price: 15,
        coin: 'g',
        icon: '',
        availability: 3,
        page: '110',
    },
    {
        name: 'Quarter Staff',
        price: 3,
        coin: 's',
        icon: '',
        availability: 6,
        page: '110',
    },

    {
        name: 'Rapier',
        price: 18,
        coin: 'g',
        icon: '',
        availability: 3,
        page: '110',
    },
    {
        name: 'Shield',
        price: 10,
        coin: 'g',
        icon: '',
        availability: 5,
        page: '110',
    },
    {
        name: 'Spear',
        price: 10,
        coin: 'g',
        icon: '',
        availability: 5,
        page: '110',
    },
    {
        name: 'Sword-breaker',
        price: 5,
        coin: 'g',
        icon: '',
        availability: 3,
        page: '110',
    }
];

export default meleeWeapons;