export default [
  {
    key: "meleeWeapons",
    label: "Melee Weapons",
    groupItems: [
      {
        name: "Buckler",
        price: 2,
        coin: "g",
        icon: "",
        availability: 4,
        page: "108",
      },
      {
        name: "Dagger",
        price: 1,
        coin: "g",
        icon: "",
        availability: 5,
        page: "108",
      },
      {
        name: "Demilance (Cavalry Spear)",
        price: 20,
        coin: "g",
        icon: "",
        availability: 3,
        page: "108",
      },
      {
        name: "Flail",
        price: 15,
        coin: "g",
        icon: "",
        availability: 3,
        page: "108",
      },
      {
        name: "Foil",
        price: 18,
        coin: "g",
        icon: "",
        availability: 2,
        page: "108",
      },
      {
        name: "Gauntlet/Knuckle-duster",
        price: 1,
        coin: "g",
        icon: "",
        availability: 5,
        page: "108",
      },
      {
        name: "Great Weapon",
        price: 20,
        coin: "g",
        icon: "",
        availability: 4,
        page: "108",
      },
      {
        name: "Halberd",
        price: 15,
        coin: "g",
        icon: "",
        availability: 5,
        page: "108",
      },
      {
        name: "Hand Weapon",
        price: 10,
        coin: "g",
        icon: "",
        availability: 5,
        page: "108",
      },
      {
        name: "Lance",
        price: 15,
        coin: "g",
        icon: "",
        availability: 2,
        page: "108",
      },
      {
        name: "Main Gauche",
        price: 4,
        coin: "g",
        icon: "",
        availability: 3,
        page: "108",
      },
      {
        name: "Morning Star",
        price: 15,
        coin: "g",
        icon: "",
        availability: 3,
        page: "108",
      },
      {
        name: "Quarter Staff",
        price: 3,
        coin: "s",
        icon: "",
        availability: 6,
        page: "108",
      },

      {
        name: "Rapier",
        price: 18,
        coin: "g",
        icon: "",
        availability: 3,
        page: "108",
      },
      {
        name: "Shield",
        price: 10,
        coin: "g",
        icon: "",
        availability: 5,
        page: "108",
      },
      {
        name: "Spear",
        price: 10,
        coin: "g",
        icon: "",
        availability: 5,
        page: "108",
      },
      {
        name: "Sword-breaker",
        price: 5,
        coin: "g",
        icon: "",
        availability: 3,
        page: "108",
      },
    ],
  },
  {
    key: "rangedWeapons",
    label: "Ranged Weapons",
    groupItems: [
      {
        name: "Blunderbuss",
        price: 70,
        availability: 3,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Bola",
        price: 7,
        availability: 3,
        coin: "s",
        icon: "",
        page: "108",
      },
      {
        name: "Bow",
        price: 10,
        availability: 5,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Crossbow",
        price: 25,
        availability: 4,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Crossbow Pistol",
        price: 35,
        availability: 2,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Elfbow",
        price: 70,
        availability: 1,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Firearm",
        price: 300,
        availability: 1,
        coin: "",
        icon: "",
        page: "108",
      },
      {
        name: "Hochland Long Rifle",
        price: 450,
        availability: 1,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Javelin",
        price: 25,
        availability: 4,
        coin: "s",
        icon: "",
        page: "108",
      },
      {
        name: "Lasso",
        price: 1,
        availability: 6,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Longbow",
        price: 15,
        availability: 4,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Net",
        price: 3,
        availability: 6,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Pistol",
        price: 200,
        availability: 1,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Repeater Crossbow",
        price: 100,
        availability: 1,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Repeater Firearm",
        price: 600,
        availability: 1,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Repeater Pistol",
        price: 400,
        availability: 1,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Shortbow",
        price: 7,
        availability: 5,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Sling",
        price: 4,
        availability: 5,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Spear",
        price: 10,
        availability: 5,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Staff Sling",
        price: 6,
        availability: 2,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Throwing Axe/Hammer",
        price: 5,
        availability: 4,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Throwing Dagger/Star",
        price: 3,
        availability: 5,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Whip",
        price: 2,
        availability: 4,
        coin: "g",
        icon: "",
        page: "108",
      },
    ],
  },
];
