export default [
  {
    key: "meleeWeapons",
    label: "Melee Weapons",
    groupItems: [
      {
        name: "Buckler",
        price: 2,
        coin: "g",
        icon: "",
        availability: 4,
        page: "108",
      },
      {
        name: "Dagger",
        price: 1,
        coin: "g",
        icon: "",
        availability: 5,
        page: "108",
      },
      {
        name: "Demilance (Cavalry Spear)",
        price: 20,
        coin: "g",
        icon: "",
        availability: 3,
        page: "108",
      },
      {
        name: "Flail",
        price: 15,
        coin: "g",
        icon: "",
        availability: 3,
        page: "108",
      },
      {
        name: "Foil",
        price: 18,
        coin: "g",
        icon: "",
        availability: 2,
        page: "108",
      },
      {
        name: "Gauntlet/Knuckle-duster",
        price: 1,
        coin: "g",
        icon: "",
        availability: 5,
        page: "108",
      },
      {
        name: "Great Weapon",
        price: 20,
        coin: "g",
        icon: "",
        availability: 4,
        page: "108",
      },
      {
        name: "Halberd",
        price: 15,
        coin: "g",
        icon: "",
        availability: 5,
        page: "108",
      },
      {
        name: "Hand Weapon",
        price: 10,
        coin: "g",
        icon: "",
        availability: 5,
        page: "108",
      },
      {
        name: "Lance",
        price: 15,
        coin: "g",
        icon: "",
        availability: 2,
        page: "108",
      },
      {
        name: "Main Gauche",
        price: 4,
        coin: "g",
        icon: "",
        availability: 3,
        page: "108",
      },
      {
        name: "Morning Star",
        price: 15,
        coin: "g",
        icon: "",
        availability: 3,
        page: "108",
      },
      {
        name: "Quarter Staff",
        price: 3,
        coin: "s",
        icon: "",
        availability: 6,
        page: "108",
      },

      {
        name: "Rapier",
        price: 18,
        coin: "g",
        icon: "",
        availability: 3,
        page: "108",
      },
      {
        name: "Shield",
        price: 10,
        coin: "g",
        icon: "",
        availability: 5,
        page: "108",
      },
      {
        name: "Spear",
        price: 10,
        coin: "g",
        icon: "",
        availability: 5,
        page: "108",
      },
      {
        name: "Sword-breaker",
        price: 5,
        coin: "g",
        icon: "",
        availability: 3,
        page: "108",
      },
    ],
  },
  {
    key: "rangedWeapons",
    label: "Ranged Weapons",
    groupItems: [
      {
        name: "Blunderbuss",
        price: 70,
        availability: 3,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Bola",
        price: 7,
        availability: 3,
        coin: "s",
        icon: "",
        page: "108",
      },
      {
        name: "Bow",
        price: 10,
        availability: 5,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Crossbow",
        price: 25,
        availability: 4,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Crossbow Pistol",
        price: 35,
        availability: 2,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Elfbow",
        price: 70,
        availability: 1,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Firearm",
        price: 300,
        availability: 1,
        coin: "",
        icon: "",
        page: "108",
      },
      {
        name: "Hochland Long Rifle",
        price: 450,
        availability: 1,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Javelin",
        price: 25,
        availability: 4,
        coin: "s",
        icon: "",
        page: "108",
      },
      {
        name: "Lasso",
        price: 1,
        availability: 6,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Longbow",
        price: 15,
        availability: 4,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Net",
        price: 3,
        availability: 6,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Pistol",
        price: 200,
        availability: 1,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Repeater Crossbow",
        price: 100,
        availability: 1,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Repeater Firearm",
        price: 600,
        availability: 1,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Repeater Pistol",
        price: 400,
        availability: 1,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Shortbow",
        price: 7,
        availability: 5,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Sling",
        price: 4,
        availability: 5,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Spear",
        price: 10,
        availability: 5,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Staff Sling",
        price: 6,
        availability: 2,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Throwing Axe/Hammer",
        price: 5,
        availability: 4,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Throwing Dagger/Star",
        price: 3,
        availability: 5,
        coin: "g",
        icon: "",
        page: "108",
      },
      {
        name: "Whip",
        price: 2,
        availability: 4,
        coin: "g",
        icon: "",
        page: "108",
      },
    ],
  },
  {
    key: "ammunition",
    label: "Ammunition",
    groupItems: [
      {
        name: "Arrows (5)",
        price: 1,
        availability: 5,
        coin: "s",
        icon: "",
        page: "108",
      },
      {
        name: "Bolts (5)",
        price: 2,
        availability: 4,
        coin: "s",
        icon: "",
        page: "108",
      },
      {
        name: "Firearm Shot (10)",
        price: 1,
        availability: 2,
        coin: "s",
        icon: "",
        page: "108",
      },
      {
        name: "Gunpowder (per shot)",
        price: 3,
        availability: 1,
        coin: "s",
        icon: "",
        page: "108",
      },
    ],
  },
  {
    key: "advancedArmour",
    label: "Advanced Armour",
    groupItems: [
      {
        name: "Leather Skullcap",
        price: 3,
        availability: 5,
        coin: "g",
        icon: "",
        page: "112",
      },
      {
        name: "Leather Jerkin",
        price: 6,
        availability: 5,
        coin: "g",
        icon: "",
        page: "112",
      },
      {
        name: "Leather Jack",
        price: 12,
        availability: 5,
        coin: "g",
        icon: "",
        page: "112",
      },
      {
        name: "Leather Leggings",
        price: 10,
        availability: 5,
        coin: "g",
        icon: "",
        page: "112",
      },
      {
        name: "Full Leather Armour",
        price: 25,
        availability: 4,
        coin: "g",
        icon: "",
        page: "112",
      },
      {
        name: "Mail Coif",
        price: 20,
        availability: 4,
        coin: "g",
        icon: "",
        page: "112",
      },
      {
        name: "Mail Shirt",
        price: 60,
        availability: 4,
        coin: "g",
        icon: "",
        page: "112",
      },
      {
        name: "Sleeved Mail Shirt",
        price: 95,
        availability: 4,
        coin: "g",
        icon: "",
        page: "112",
      },
      {
        name: "Mail Coat",
        price: 75,
        availability: 4,
        coin: "g",
        icon: "",
        page: "112",
      },
      {
        name: "Sleeved Mail Coat",
        price: 130,
        availability: 4,
        coin: "g",
        icon: "",
        page: "112",
      },
      {
        name: "Mail Leggings",
        price: 20,
        availability: 3,
        coin: "g",
        icon: "",
        page: "112",
      },
      {
        name: "Full Mail Armour",
        price: 170,
        availability: 3,
        coin: "g",
        icon: "",
        page: "112",
      },
      {
        name: "Helmet",
        price: 30,
        availability: 3,
        coin: "g",
        icon: "",
        page: "112",
      },
      {
        name: "Breastplate",
        price: 70,
        availability: 3,
        coin: "g",
        icon: "",
        page: "112",
      },
      {
        name: "Plate Bracers",
        price: 60,
        availability: 3,
        coin: "g",
        icon: "",
        page: "112",
      },
      {
        name: "Plate Leggings",
        price: 70,
        availability: 3,
        coin: "g",
        icon: "",
        page: "112",
      },
      {
        name: "Full Plate Armour",
        price: 400,
        availability: 2,
        coin: "g",
        icon: "",
        page: "112",
      },
    ],
  },
];
